### ISSUE TITLE
ec2_lc devel - bug introduced with 8a9405a ?

### ISSUE THREAD

**Issue by halberom** [ansible/ansible-modules-core#1848]
Relates to 8a9405a55bc5ac814b6e952acd2df0a6467e8a27

version

```
$ ansible-playbook --version
ansible-playbook 2.0.0 (devel b37be236d9) last updated 2015/07/30 10:39:21 (GMT +100)
```

error seen

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/glynch/.ansible/tmp/ansible-tmp-1438349622.67-106821975744135/ec2_lc", line 2209, in <module>
    main()
  File "/Users/glynch/.ansible/tmp/ansible-tmp-1438349622.67-106821975744135/ec2_lc", line 2205, in main
    create_launch_config(connection, module)
  File "/Users/glynch/.ansible/tmp/ansible-tmp-1438349622.67-106821975744135/ec2_lc", line 2148, in create_launch_config
    module.exit_json(changed=changed, name=result.name, created_time=str(result.created_time),
AttributeError: 'dict' object has no attribute 'name'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```

doing a pdb trace gives

```
$ python /Users/glynch/.ansible/tmp/ansible-tmp-1438349622.67-106821975744135/ec2_lc
> /Users/glynch/.ansible/tmp/ansible-tmp-1438349622.67-106821975744135/ec2_lc(2150)create_launch_config()
-> module.exit_json(changed=changed, name=result.name, created_time=str(result.created_time),
(Pdb) p result
{'a': 's', 'c': 'o', 'b': 'l', 'e': 'b', 'd': 'e', 'i': 'n', 'k': 'e', 'm': 'e', 'l': 'a', 'n': 'a', 's': 'p', 'r': 'a', 'u': 's', 'v': 'o'}
```

Seems the `result` dict manipulation is splitting on the chars.

Looking at `result` before the dict manipulation, it's an object

```
(Pdb) p result
LaunchConfiguration:mofaman_nat_asg_lc
(Pdb) dir(result)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'associate_public_ip_address', 'block_device_mappings', 'classic_link_vpc_id', 'classic_link_vpc_security_groups', 'connection', 'created_time', 'delete', 'delete_on_termination', 'ebs_optimized', 'endElement', 'image_id', 'instance_monitoring', 'instance_profile_name', 'instance_type', 'iops', 'kernel_id', 'key_name', 'launch_configuration_arn', 'member', 'name', 'ramdisk_id', 'security_groups', 'spot_price', 'startElement', 'use_block_device_types', 'user_data', 'volume_type']
(Pdb) result.name
u'mofaman_nat_asg_lc'
(Pdb) result.created_time
datetime.datetime(2015, 7, 31, 10, 4, 19, 305000)
```

I'm not sure what's required for it to be sent to jsonify, will dig a bit more

More info showing the launch_config content.

```
(Pdb) p vars(launch_configs[0])
{'ramdisk_id': '', 'user_data': '#!/bin/bash\n\ncat > /root/nat_configs.txt <<EOF\neipalloc-5882a23d,subnet-866e5af1,rtb-f38a4497\neipalloc-5282a237,subnet-a816f395,rtb-ff8a449b\nEOF\n\n# make sure nat settings are in place\niptables -t nat -A POSTROUTING -j MASQUERADE\niptables -A FORWARD -j ACCEPT\necho 1 > /proc/sys/net/ipv4/ip_forward\n\ncurl -sL https://raw.githubusercontent.com/HighOps/ec2-nat-failover/master/nat_monitor.py > /root/nat_monitor.py\npython -u /root/nat_monitor.py < /root/nat_configs.txt | logger -t nat_monitor\n\n', 'iops': None, 'created_time': datetime.datetime(2015, 7, 31, 10, 4, 19, 305000), 'classic_link_vpc_id': None, 'security_groups': [u'sg-bdcd7ada'], 'spot_price': None, 'ebs_optimized': False, 'member': u'\n      ', 'classic_link_vpc_security_groups': [], 'delete_on_termination': True, 'kernel_id': '', 'key_name': u'ssh_key', 'associate_public_ip_address': True, 'image_id': u'ami-303b1458', 'instance_monitoring': InstanceMonitoring(false), 'block_device_mappings': [], 'name': u'mofaman_nat_asg_lc', 'instance_profile_name': u'NATMonitor', 'volume_type': None, 'instance_type': u't2.small', 'connection': AutoScaleConnection:autoscaling.us-east-1.amazonaws.com, 'use_block_device_types': False, 'launch_configuration_arn': u'arn:aws:autoscaling:us-east-1:982212772075:launchConfiguration:0840b62d-0fd0-4fc2-ab2f-f254649c64aa:launchConfigurationName/mofaman_nat_asg_lc'}
```

**Comment by bcoca** [comment]
cc @abadger

**Comment by halberom** [comment]
works (sortof), if I do

```
result = dict(((k,v) for k,v in vars(launch_configs[0]).iteritems() if k not in ('connection',)))
```

although object attribute access doesn't work anymore. so it's necessary to do, e.g. 

```
(Pdb) result['created_time']
datetime.datetime(2015, 7, 31, 10, 4, 19, 305000)
```

**Comment by halberom** [comment]
although then it tries to serialise the created_time in the result param, and it barfs with

```
TypeError: datetime.datetime(2015, 7, 31, 10, 4, 19, 305000) is not JSON serializable
```

that's with

```
    result = launch_configs[0]
    result_dict = dict(((k,v) for k,v in vars(launch_configs[0]).iteritems() if k not in ('connection',)))

    module.exit_json(changed=changed, name=result.name, created_time=str(result.created_time),
                     image_id=result.image_id, arn=result.launch_configuration_arn,
                     security_groups=result.security_groups,
                     instance_type=result.instance_type,
                     result=result_dict)
```

so maybe the datetime should be excluded as well, given it's handled with a separate kwarg.

**Comment by halberom** [comment]
I've not done a full bisect, but it works at 28a869a030fb3be9818c71e08.

**Comment by abadger** [comment]
@halberom I have no ability to test this but your changes sound correct.  I'll make them and you can test them and close this bug if it works.

**Comment by halberom** [comment]
Hey @abadger, thanks, i've just tested and got

```
TypeError: InstanceMonitoring(false) is not JSON serializable
```

adding instance_monitor to the list of ones to exclude works.  And that's the last one.

**Comment by abadger** [comment]
@halberom okay,  that last commit should fix instance_monitoring as well.  Feel free to ping me on IRC or open a new bug if you run into more fields that need explicit serialization later!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
