### ISSUE TITLE
NoneType Object Exception in S3 module

### ISSUE THREAD

**Issue by juliedavila** [ansible/ansible-modules-core#964]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.4 and 

```
ansible 1.9.0 (detached HEAD bce4bb2ce2) last updated 2015/03/18 17:03:10 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 31cc5f543f) last updated 2015/03/16 12:19:43 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 8baba98ebe) last updated 2015/03/16 12:19:43 (GMT -400)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/03/16 12:19:43 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 46e316a20a) last updated 2015/03/16 12:19:44 (GMT -400)
  configured module search path = None
```
##### Environment:

OSX
##### Summary:

Seems that the instantiation of the S3 connection object is faulty.
##### Steps To Reproduce:

Run this playbook (note: also attempted with put with the same outcome):

```

---
- name: Spin up instances for testing
  connection: local
  hosts: localhost
  tasks:
     - name: s3s3
       s3:
        bucket: deleteme
        aws_access_key: '{{ access }}'
        aws_secret_key: '{{ secret }}'
        mode: create
```
##### Expected Results:

The bucket gets created.
##### Actual Results:

```
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/jdavila/.ansible/tmp/ansible-tmp-1426712862.59-255191123006590/s3", line 2299, in <module>
    main()
  File "/Users/jdavila/.ansible/tmp/ansible-tmp-1426712862.59-255191123006590/s3", line 452, in main
    bucketrtn = bucket_check(module, s3, bucket)
  File "/Users/jdavila/.ansible/tmp/ansible-tmp-1426712862.59-255191123006590/s3", line 162, in bucket_check
    except s3.provider.storage_response_error, e:
AttributeError: 'NoneType' object has no attribute 'provider'


FATAL: all hosts have already failed -- aborting
```

**Comment by robzienert** [comment]
+1 ... with the PPA repo getting bumped to 1.9.0, this broke all of our provisioning scripts. This was not an issue in 1.8.4 for me.

**Comment by bcoca** [comment]
so the only reason I can fathom for s3 being None at this point is that the connection failed to happen and did not cause an Exception. ... using the object being handled in the exception handler ....gets us here.

**Comment by bcoca** [comment]
try using this version:
https://github.com/bcoca/ansible-modules-core/blob/s3_exception_fix/cloud/amazon/s3.py

**Comment by smarmit** [comment]
+1

1.9.0.1 broke S3 gets for us as well.

**Comment by bcoca** [comment]
could this be related?
https://github.com/ansible/ansible-modules-core/issues/69

above I just fix the error reporting

**Comment by juliedavila** [comment]
@bcoca different issue. #69 has to do with the fact that in IAM you can have permissions to access a bucket but not necessarily to list said bucket which causes an issue forcing users to add list permissions in order to use the module.

This is an independent issue.

**Comment by bcoca** [comment]
since we are failing in the bucket lookup and I'm not familiar with all the changes that wen't into the s3 module I was wondering if this was the cause.

have you tested with my code?

**Comment by robzienert** [comment]
I'll be looking into this today. My guess is that it's with ansible core, rather than the s3 module itself. The None type is the s3 connection, so it is likely affecting all of the Amazon modules. I'll explore both the branch and also peek around in module utils WRT establishing connections.

**Comment by juliedavila** [comment]
@bcoca yeah tried your code, still is failing where it shouldn't. Just provides your error message instead of the NoneType exception msg. This is def a higher priority bug IMO, I'm looking into this deeper now.

I still get it with the 1.8.4 checkout. Doing some bisecting...

**Comment by robzienert** [comment]
The bug was introduced in this commit: https://github.com/ansible/ansible-modules-core/commit/60e2e43f003ab14f33936ba4aee19699d60db546

Looks like this is a bug in boto itself, but Ansible forces anyone using `us-east-1` S3 buckets to hit it. Boto's `Location.DEFAULT` is an empty string, which causes `boto.s3.connect_to_region` to return a NoneType connection. Manually setting my custom S3 modules to declare `us-east-1` returns an S3 connection.

Since the S3 module forces `us-east-1` to become `Location.DEFAULT`, any use of us-east-1 will fail.

I think we should merge that S3 exception branch, as well as removing this block until the bug in boto is fixed: https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/s3.py#L306-312

**Comment by juliedavila** [comment]
Hmm, is Boto tracking this issue?

**Comment by robzienert** [comment]
Now it is. I wasn't able to find any issue related to it.

**Comment by juliedavila** [comment]
Looking at the boto docs it looks like that could be intentional behavior https://boto.readthedocs.org/en/2.0/s3_tut.html#creating-a-bucket-in-another-location

This issue _might_ not be impacting AWS accounts that have access the US Classic Region. (The accounts created before the VPC-only change at AWS)

I'd recommend removing the block you referenced above along with @bcoca's exception handling AND making the region a required param.

**Comment by bcoca** [comment]
I'll update my code with that revert and create a PR

**Comment by bcoca** [comment]
instead of a full revert i set it as a fallback, please test PR #1004 

I'm also making a note to get a 'new' aws account as it seems we are using 'classic' ones and did not realize there was a big difference

**Comment by dchancogne** [comment]
Awesome. Scratched my head for a while until I found this. Thanks.
Will this be build to https://launchpad.net/~ansible/+archive/ubuntu/ansible as 1.9.0.2 soon?

**Comment by magnetik** [comment]
Not confirming as fix for me. 

I'm using IAM profile that was working with ansible 1.8, and fall into the fail 'Unknown error, failed to create s3 connection, no information from boto.'

[edit] but it's working when I specify the region in the module call

**Comment by robzienert** [comment]
Are you in VPC or EC2 classic?

**Comment by mmcallister** [comment]
We got these same errors after upgrading to v1.9.0.1. We are in VPC.
Rolling back to 1.8.4 fixed this.

e.x.
 {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-xxxx/s3", line 2299, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-xxxx/s3", line 405, in main
    bucketrtn = bucket_check(module, s3, bucket)
  File "/root/.ansible/tmp/ansible-tmp-xxxx/s3", line 162, in bucket_check
    except s3.provider.storage_response_error, e:
AttributeError: 'NoneType' object has no attribute 'provider'

**Comment by bcoca** [comment]
@mmcallister try current devel

**Comment by splisson-altair** [comment]
This is really blocking, any workaround ?

**Comment by juliedavila** [comment]
@splisson-altair have you tried this in devel? I no longer have the issue.

**Comment by splisson-altair** [comment]
@defionscode I look into installing devel branch and try again.  thanks

**Comment by clebio** [comment]
While not a solution, our work-around has been:

```
- name: Copy file from S3
  command: aws s3 cp "s3://bucket/{{ item }}" "/home/ubuntu/{{ item }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    AWS_SECURITY_TOKEN: "{{ lookup('env','AWS_SECURITY_TOKEN') }}"
    AWS_DEFAULT_REGION: "{{ aws_default_region }}"
  with_items:
    - file_on_s3.ext
```

(which of course requires the `awscli` package on the target machine.)

**Comment by juliedavila** [comment]
@splisson-altair  Ok cool, if it works in devel then what you could do in the interim is copy the s3.py directly from source into `$PROJECT_ROOT/library/s3.py` that way you can stay in stable while leveraging the latest s3 until the next release.

@clebio do you still see this in devel? or is that a workaround while being on stable?

**Comment by splisson-altair** [comment]
@defionscode now I get "msg: Failed to connect to S3: global name 'aws_access_key' is not defined" even though the key is defined as environment variable AWS_ACCESS_KEY

**Comment by juliedavila** [comment]
@splisson-altair I am assuming you typo'd `AWS_ACCESS_KEY` so I'm gonna try to replicate real quick...un momento

**Comment by juliedavila** [comment]
my current working way has the boto creds in ~/.boto (which may help in the iterim)

**Comment by juliedavila** [comment]
@splisson-altair was not able to replicate (moved my boto config away to test), could you make sure you have `AWS_ACCESS_KEY` and `AWS_SECRET_KEY` in your env?

**Comment by splisson-altair** [comment]
The environment variables are set but aws_access_key remains undefined

**Comment by bcoca** [comment]
aws_access_key is a parameter, it is not a variable and should not appear as undefined, at most it should get a NoneType exception. are you setting/passing it yourself? can you show the task?

**Comment by splisson-altair** [comment]
```
- name: Fetch file from S3
  s3: region=us-east-1 bucket=testbucket object=/file.jpg mode=get
```

**Comment by juliedavila** [comment]
Looks like he is hitting the exception on line 335, still odd to me. It works with my boto profile and it works when use environment variables, i can't replicate this at all.

**Comment by juliedavila** [comment]
Looking at it, the only way you should be getting that error is if you're using an old version of s3.py. Try to curl https://raw.githubusercontent.com/ansible/ansible-modules-core/devel/cloud/amazon/s3.py into your `$YOUR_PROJECT_ROOT/library/` directory

**Comment by splisson-altair** [comment]
This one is a bit different, now I get: 
msg: No Authentication Handler found: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials

**Comment by splisson-altair** [comment]
If I pass the credentials explicitly to the s3 module, it works.
I forgot to mention, I'm testing this on vagrant maybe the local environment variables are not passed to the vagrant machine.
So the s3.py is fine now it's just a matter of passing the credentials to the VM

**Comment by joantune** [comment]
Guys. I ran into the same error.

I'm a bit of a Python newbie and I'm just learning ansible, so, before trying @clebio 's workaround I tried replacing the s3.py on my **local machine** to no result. I did it on `/usr/local/lib/python2.7/site-packages/ansible/modules/core/cloud/amazon` and appended the `_backup` to the files `s3.py` and `s3.pyc` and then did a curl (actually wget) to get the new `s3.py` but the fact that there is no new `s3.pyc` makes me think that the new version wasn't used (plus the error persisted).  I'm probably doing something wrong. Have I replaced the right files? Is there a remote s3.py counterpart on the destination machine? anyway, if you guys want another confirmation or not if the new code is working, let me know what I should do and I'll try it out.

Meanwhile, @clebio, Thanks for the workaround. I added an extra:

```
 - name: make sure that the AWS client is installed
      apt: name=awscli state=present
```

to make sure that not having aws cli is not a problem.

Cheers

**Comment by bennojoy** [comment]
@joantune  the easiest way would be to create a directory "library" in the same level as your main playbook and add the new module there, ansible then should pickup the new module instead of the old one.

**Comment by joantune** [comment]
@bennojoy indeed! thanks.

@defionscode: I can confirm that the s3.py from https://raw.githubusercontent.com/ansible/ansible-modules-core/devel/cloud/amazon/s3.py  does not solve the problem. To make sure that I was using that one I even wrote a random line in that file and did got a compilation error (meaning I'm using that version)
