### PR TITLE
When no use_tls is not specified and no tls parameters are given we need to not attempt tls.

### PR DESCRIPTION
**Pull request by abadger**
From the error in #940 it looks like we need to set tls_config=None in more cases.  This is a fix for one common case in the tls features introduced with #926

### CODE REVIEW

**Comment by abadger** [comment]
I think this is a necessary fix so I'm going to merge this to devel and stable-1.9 now.  @smashwilson, @dguerri, @lorin if this causes problem with your usage of boot2docker (or any other tls stuff), please let me know ASAP.

**Comment by dguerri** [comment]
Working as expected here with `use_tls=verify`

**Comment by dguerri** [comment]
And this is what I am getting without environment and explicit settings about TLS verification:

Using tcp:// uri

```
TASK: [Start Auto-DNS container] ********************************************** 
failed: [localhost] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',)),)
```

Using https:// uri

```
TASK: [Start Auto-DNS container] ********************************************** 
failed: [localhost] => {"changed": false, "failed": true}
msg: SSLError(SSLError(SSLError(1, '_ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version'),),)
```

**Comment by abadger** [comment]
@dguerri Okay, I've now merged this fix to devel and stable-1.9 and updated the module repo pointers in the ansible/ansible repository.  Do you still get those Connection/SSL errors?

**Comment by dguerri** [comment]
Sorry I expressed myself badly. Those errors were expected because I disabled tls and tried to connect to a tls-enabled docker!

**Comment by abadger** [comment]
Ah.  Cool, so it all works :-)
