### ISSUE TITLE
Ansible v2.1.2.0 cron module: job Required if state=absent result in error

### ISSUE THREAD

**Issue by StevendeVries** [ansible/ansible-modules-core#5150]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

Cron module
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /Users/stevendevries/somewhere/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I want to make sure an old cronjob is not present anymore, using the following task:

```
- name: Make sure an old cronjob is not present anymore
  cron: name="aws_scripts_mon" user="{{ ansible_user }}" state=absent
```

This works fine with Ansible 2.1.1.0 after updating to 2.1.2.0 this breaks.
##### STEPS TO REPRODUCE

Run this task and it fails:

```
- name: Make sure an old cronjob is not present anymore
  cron: name="aws_scripts_mon" user="{{ ansible_user }}" state=absent
```

Run this task and it works (just a random string in job parameter)

```
- name: Make sure an old cronjob is not present anymore
  cron: name="aws_scripts_mon" job="something" user="{{ ansible_user }}" state=absent
```
##### EXPECTED RESULTS

I should work without a job parameter.
##### ACTUAL RESULTS

```
TASK [aws : Make sure an old cronjob is not present anymore] *******************
task path: /srv/http/mmim-leveranciersportaal/ansible/roles/aws/tasks/main.yml:43
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'strip'
fatal: [somewhere]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_yPdq_U/ansible_module_cron.py\", line 700, in <module>\n    main()\n  File \"/tmp/ansible_yPdq_U/ansible_module_cron.py\", line 645, in main\n    job = crontab.get_cron_job(minute, hour, day, month, weekday, job, special_time, disabled)\n  File \"/tmp/ansible_yPdq_U/ansible_module_cron.py\", line 385, in get_cron_job\n    job = job.strip('\\r\\n')\nAttributeError: 'NoneType' object has no attribute 'strip'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

My best guess would be to move line: 
https://github.com/ansible/ansible-modules-core/blob/17ee1cfaf960d99bd3fee7631f86b1013957ec70/system/cron.py#L645
to:
https://github.com/ansible/ansible-modules-core/blob/17ee1cfaf960d99bd3fee7631f86b1013957ec70/system/cron.py#L649

**Comment by ansibot** [comment]
@dsummersl, @EvanK, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dvershinin** [comment]
+1. I experience the same issue. The cron removal fails, unless "job" is specified.

**Comment by EvanK** [comment]
This will be resolved_by_pr #5151 (currently marked for inclusion but not yet merged)

**Comment by StevendeVries** [comment]
As stated: This will be resolved_by_pr #5151
