### ISSUE TITLE
ec2_ami: AttributeError: 'BlockDeviceType' object has no attribute 'encrypted'

### ISSUE THREAD

**Issue by bryanlarsen** [ansible/ansible-modules-core#5256]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2_ami
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

doesn't work from: Ubuntu 14.04, with python2.7-boto 2.20.1-2ubuntu2
works from: Ubuntu 16.04, with 2.38.0-1ubuntu1
to: Ubuntu 16.04 on AWS
##### SUMMARY

ec2_ami doesn't work on Ubuntu 14.04, works fine on 16.04

I suspect python-boto might be the problem.  14.04 uses 2.20.1-2ubuntu2, 16.04 uses 2.38.0-1ubuntu1

##### STEPS TO REPRODUCE

```
    - ec2_ami:
        instance_id: "{{ awsInstanceId }}"
        region: "{{ awsRegion }}"
        ec2_access_key: "{{ hostvars[apiHost]['ec2_access_key'] }}"
        ec2_secret_key: "{{ hostvars[apiHost]['ec2_secret_key'] }}"
        wait: true
        name: "{{gitsha}}-{{templateName}}"
        wait_timeout: 3600
      register: ami
```

##### ACTUAL RESULTS

```
fatal: [production-worker-template.clara.io]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Uk8_mk/ansible_module_ec2_ami.py\", line 560, in <module>\n    main()\n  File \"/tmp/ansible_Uk8_mk/ansible_module_ec2_ami.py\", line 552, in main\n    create_image(module, ec2)\n  File \"/tmp/ansible_Uk8_mk/ansible_module_ec2_ami.py\", line 419, in create_image\n    module.exit_json(msg=\"AMI creation operation complete\", changed=True, **get_ami_info(img))\n  File \"/tmp/ansible_Uk8_mk/ansible_module_ec2_ami.py\", line 331, in get_ami_info\n    block_device_mapping=get_block_device_mapping(image),\n  File \"/tmp/ansible_Uk8_mk/ansible_module_ec2_ami.py\", line 318, in get_block_device_mapping\n    'encrypted': bdm[device_name].encrypted,\nAttributeError: 'BlockDeviceType' object has no attribute 'encrypted'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by ansibot** [comment]
@jjshoe ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jjshoe, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jjshoe, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jjshoe, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by ansibot** [comment]
This issue was migrated to https://github.com/ansible/ansible/issues/29583
