### ISSUE TITLE
Error in handling docker container simple volumes

### ISSUE THREAD

**Issue by omriiluz** [ansible/ansible-modules-core#1957]
##### Ansible Version:

Latest dev

ansible 2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
##### Ansible Configuration:

No changes from default
##### Environment:

Running from Ubuntu 15.04, Target CoreOS 766.1.0
##### Summary:

Ansible fails when trying to compare expected volumes of docker container vs. deployed due to a bug in list handling introduced by https://github.com/ansible/ansible-modules-core/commit/c3f92cca210db1f7042bfce1ff90645255f0b49e 
##### Steps To Reproduce:

Deploy a docker container that includes a simple volume (not binded volume):

```
- name: application container
  docker:
    name: myapplication
    image: someuser/appimage
    state: reloaded
    pull: always
    volumes:
    - /root
```

It will deploy successfully. Run a second time with no changes to config or parameters. 
##### Expected Results:

Ansible should finish without making changes or failing.
##### Actual Results:

Ansible fails with the following error:

```
Traceback (most recent call last):\r\n  File \"app_main.py\", line 75, in run_toplevel\r\n  File \"/home/omri/.ansible/tmp/ansible-tmp-1440317509.28-73677038538833/docker\", line 3443, in <module>\r\n    main()\r\n  File \"/home/omri/.ansible/tmp/ansible-tmp-1440317509.28-73677038538833/docker\", line 1711, in main\r\n    reloaded(manager, containers, count, name)\r\n  File \"/home/omri/.ansible/tmp/ansible-tmp-1440317509.28-73677038538833/docker\", line 1576, in reloaded\r\n    for container in manager.get_differing_containers():\r\n  File \"/home/omri/.ansible/tmp/ansible-tmp-1440317509.28-73677038538833/docker\", line 1024, in get_differing_containers\r\n    expected_volume_keys.update(self.volumes.keys())\r\nAttributeError: 'list' object has no attribute 'keys'\r\n", "parsed": false
```

**Comment by omriiluz** [comment]
Resolved with PR https://github.com/ansible/ansible-modules-core/pull/1958

**Comment by bcoca** [comment]
closed via #1958
