### ISSUE TITLE
synchronize: option 'mode' is not recognized in v2

### ISSUE THREAD

**Issue by ZviRackover** [ansible/ansible-modules-core#1783]
Issue Type: Bug Report
Ansible Version: 2.0
Environment: Ubuntu 14.04
Summary:

According to the doc at http://docs.ansible.com/ansible/synchronize_module.html#options there is an option 'mode' which seems to be unsupported. Looking at https://github.com/ansible/ansible-modules-core/blob/devel/files/synchronize.py you can see that the doc section describes the 'mode' option, but the code does not implement it.

So it seems that either the documentation needs to be updated, or this feature needs to be implemented.

**Comment by abadger** [comment]
Mode is implemented here: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/synchronize.py#L105

synchronize and other modules that you see in that same action directory need at least a portion to be run on the controller side.  The documentation, is all in the module itself, however.

Is there something about mode that isn't working work you?

**Comment by ZviRackover** [comment]
Here is the task that is causing the problem:
    - name: Sync system files from Raspberry pi
      synchronize: src={{ device_host }}:/{{ item }}
        dest={{ top_dir }}/rootfs
        recursive=yes
        links=yes
        delete=yes
        rsync_opts=--safe-links
        mode=pull
      with_items:
        - usr
        - lib

Here is the error message i see:

fatal: [default]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "One or more items failed",
    "results": [
        {
            "failed": true,
            "item": "usr",
            "msg": "unsupported parameter for module: mode"
        },
        {
            "failed": true,
            "item": "lib",
            "msg": "unsupported parameter for module: mode"
        }
    ]
}

If i remove the 'mode=pull' from the task definition there is no error.

**Comment by abadger** [comment]
Confirmed -- Made a slightly simpler playbook that worked on 1.9.2 and failed with the same error on 2.0

**Comment by abadger** [comment]
Okay, this particular issue should be fixed by my commit above.  However, in testing that, I ran into the second part of this issue: https://github.com/ansible/ansible/issues/11649  It seems like the synchronize module is currently copying between source and dest on the remote machine rather than the local machine and the remote machine.Will need to fix that ticket before the synchronize module in v2 becomes useful again.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
