### ISSUE TITLE
S3: 'module' object has no attribute 'connect_to_region'

### ISSUE THREAD

**Issue by samyray** [ansible/ansible-modules-core#1544]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.1
##### Environment:

OSX 10.9.5 and Ubuntu 12.04
##### Summary:

Connection to the S3 is failing (we are using eu-west-1 if this matters)
##### Steps To Reproduce:

Run this playbook

```
- hosts: {{Remote_host}}
  tasks:
    - name: 's3'
      s3: bucket=test_bucket object=test_object aws_access_key={{ lookup('env','AWS_ACCESS_KEY') }} aws_secret_key={{ lookup('env','AWS_SECRET_KEY') }} mode=create region=eu-west-1
```
##### Expected Results:

The bucket gets created.
##### Actual Results:

```
failed: [Remote_host] => {"failed": true}
msg: Failed to connect to S3: 'module' object has no attribute 'connect_to_region'

FATAL: all hosts have already failed -- aborting
```

**Comment by bennojoy** [comment]
@samyray can you please try with latest devel and let us know if you have the same issue there.

**Comment by samyray** [comment]
@bennojoy thanks for looking, just tried with below version:

```
ansible-playbook 2.0.0 (devel 7c65f3ddd7) last updated 2015/06/18 13:43:57 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 9acc7c402f) last updated 2015/06/18 13:44:03 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 2f967a949f) last updated 2015/06/18 13:44:09 (GMT +000)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/18 13:44:15 (GMT +000)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/18 13:44:23 (GMT +000)
  configured module search path = None
```

And got the same result:

```
fatal: [Remote_host]: FAILED! => {"msg": "Failed to connect to S3: 'module' object has no attribute 'connect_to_region'", "failed": true, "changed": false, "invocation": {"module_name": "s3", "module_args": {"aws_secret_key": "", "aws_access_key": "", "region": "eu-west-1", "object": "test_object", "bucket": "test_bucket", "mode": "create"}}}
```

btw, it works fine on ansible 1.7.2 (don't have any other versions to check unfortunately)

**Comment by bennojoy** [comment]
@samyray from your output seems like it is not able to connect to s3, does you system have internet access ? also i am not able to reproduce this.

**Comment by shay-li** [comment]
Reproduce 

Ansible Version:
1.9.1
OS:
Ubuntu 14.04

What`s the status of this bug?

**Comment by jsabo** [comment]
I'm seeing the same issue but it's only happening to me on Ubuntu.

**Comment by erikkri** [comment]
This happens because ubuntu is running boto 2.2. Check this for details: http://stackoverflow.com/questions/22718987/want-to-connect-to-dynamodb-get-attributeerror-module-object-has-no-attribut

**Comment by romanr** [comment]
I was able to fix it by logging in to target host and running `sudo pip install boto --upgrade`

**Comment by ansibot** [comment]
@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by danvaida** [comment]
FWIW, I'm also seeing this on `devel` and on `stable-2.1`:
```
$ ansible --version
ansible 2.2.0 (devel ff52e01a11) last updated 2016/09/19 11:27:43 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 488f082761) last updated 2016/09/19 11:27:53 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 24da3602c6) last updated 2016/09/19 11:27:53 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
```
```
$ ansible --version
ansible 2.1.2.0 (stable-2.1 fc3efdb057) last updated 2016/08/25 13:45:02 (GMT +200)
  lib/ansible/modules/core: (detached HEAD edbd108b15) last updated 2016/09/19 11:30:20 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 503158a82c) last updated 2016/09/19 11:30:20 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
```

Example of task that works:
```
    - name: Tarball name should be obtained
      s3:
        aws_access_key: "{{ deploy_aws_access_key }}"
        aws_secret_key: "{{ deploy_aws_secret_key }}"
        bucket: "{{ deploy_s3_bucket }}"
        mode: list
        prefix: "{{ deploy_package }}"
        region: 'eu-central-1'
      register: tarball_name
```

And here's an example of task that doesn't work:

```
    - name: Deploy tarball should be downloaded
      s3:
        aws_access_key: "{{ deploy_aws_access_key }}"
        aws_secret_key: "{{ deploy_aws_secret_key }}"
        bucket: "{{ deploy_s3_bucket }}"
        object: "{{ deploy_file_name }}.tar"
        dest: "{{ deploy_project_root }}/shared/source/{{ deploy_file_name }}.tar"
        mode: get
      region: 'eu-central-1'
```

Boto:

```
$ sudo pip freeze | grep boto
Password:
boto==2.42.0
boto3==1.4.0
botocore==1.4.43
```

Haven't had the time yet to investigate this...

**Comment by ansibot** [comment]
@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by ansibot** [comment]
This issue was migrated to https://github.com/ansible/ansible/issues/30110

**Comment by BenCoffeed** [comment]
For those coming along after, I was able to resolve this issue by using the pip module to install boto components. The pip libraries have newer versions of boto, boto3, and boto-core that seem to resolve the issues. 

`roles/common/defaults/main.yml`
```yml
. . .
defaults:
  required_apt:
    - python-pip

  required_pip:
    - pip
    - boto
    - botocore
    - boto3
. . .
```

`roles/common/tasks/main.yml
```yml
. . .
- name: Install common pre-reqs
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ defaults.required_apt }}"

- name: Install common Python pre-reqs
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ defaults.required_pip }}"
. . .
```
