### PR TITLE
5150 Cron module: Move job parameter to meet expected requirements

### PR DESCRIPTION
**Pull request by StevendeVries**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

Cron

Details in #5150 :
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /Users/stevendevries/somewhere/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I want to make sure an old cronjob is not present anymore, using the following task:

```
- name: Make sure an old cronjob is not present anymore
  cron: name="aws_scripts_mon" user="{{ ansible_user }}" state=absent
```

This works fine with Ansible 2.1.1.0 after updating to 2.1.2.0 this breaks.
##### STEPS TO REPRODUCE

Run this task and it fails:

```
- name: Make sure an old cronjob is not present anymore
  cron: name="aws_scripts_mon" user="{{ ansible_user }}" state=absent
```

Run this task and it works (just a random string in job parameter)

```
- name: Make sure an old cronjob is not present anymore
  cron: name="aws_scripts_mon" job="something" user="{{ ansible_user }}" state=absent
```
##### EXPECTED RESULTS

I should work without a job parameter.
##### ACTUAL RESULTS

```
TASK [aws : Make sure an old cronjob is not present anymore] *******************
task path: /srv/http/mmim-leveranciersportaal/ansible/roles/aws/tasks/main.yml:43
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'strip'
fatal: [somewhere]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_yPdq_U/ansible_module_cron.py\", line 700, in <module>\n    main()\n  File \"/tmp/ansible_yPdq_U/ansible_module_cron.py\", line 645, in main\n    job = crontab.get_cron_job(minute, hour, day, month, weekday, job, special_time, disabled)\n  File \"/tmp/ansible_yPdq_U/ansible_module_cron.py\", line 385, in get_cron_job\n    job = job.strip('\\r\\n')\nAttributeError: 'NoneType' object has no attribute 'strip'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @StevendeVries. To the current maintainers, @dsummersl, @EvanK please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EvanK** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @StevendeVries for this PR, and thanks @dsummersl, @EvanK for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]
